### ISSUE TITLE
Petit problème

### ISSUE THREAD

**Issue by Miragedediscord** [JacqueSatan/Discord-bot#12]
Quand je suis sur le launcher, je veux vérifier le rôle de mon bot, je clique sur "vérifier le rôle du bot" et là il y a marquer "une erreur c'est produite". Donc j'aimerai savoir pourquoi sa me marque "une erreur c'est produite" svp. Merci.

**Comment by Miragedediscord** [comment]
Merci de votre réponse mon problème est régler.

**Comment by Qubat08** [comment]
Bonjour, j'ai testé le bot sur un serveur rempli d'alt (facile à faire) et le ban tous le monde ne fonctionne pas. Je m'explique;
Quand j'appui sur le bouton bannir tous le monde, l'attaque se lance etc et le bot ban personne. Je ne sais pas si cela me le fait qu'à moi.
Cordialement
