### ISSUE TITLE
Bug depandance

### ISSUE THREAD

**Issue by LuZrOg0** [JacqueSatan/Discord-bot#13]
J'installe les dépendances mais ça me mets que je l'ai ai pas installer.

**Comment by JacqueSatan** [comment]
Peux-tu nous fournir plus d'informations ?

**Comment by Qubat08** [comment]
Bonjour.
Je ne sais pas qu'est-ce que les Dépendances.
 Aussi quand j'essaye de lancer une attaque (avec toutes les bonnes informations)
J'ai un message d'erreur dans la console qui me dit qu'il ne trouve pas Discord.js
Cannot find module 'discord.js'
