### ISSUE TITLE
bug au niveau du ban

### ISSUE THREAD

**Issue by Qubat08** [JacqueSatan/Discord-bot#14]
Bonjour, j'ai testé le bot sur un serveur rempli d'alt (facile à faire) et le ban tous le monde ne fonctionne pas. Je m'explique;
Quand j'appui sur le bouton bannir tous le monde, l'attaque se lance etc et le bot ban personne. Je ne sais pas si cela me le fait qu'à moi.
Cordialement

**Comment by JacqueSatan** [comment]
Bonsoir, je suis vraiment désolé mais le développement de cette application a été interrompu il y a plusieurs mois, peux-tu m'envoyer les logs de la console quand tu fais la même manipulation avec debug_mode.bat ?
