### ISSUE TITLE
Petit bug qui fait tout buger 

### ISSUE THREAD

**Issue by Kostokiller** [JacqueSatan/Discord-bot#15]
**Décrivez l'erreur**

Quand je lance l'attaque tout se passe bien , quand d'un coup  "Error : Cannot find module "Discord j.s" 
Aider moi svp ! 😭 

Si l'unes des personnes qui pourrait m'aider à Discord qu'il me l'envoie en privée pour que je lui indique plus en détails ma situation.

**Comment by JacqueSatan** [comment]
Bonjour, il te suffit simplement de cliquer sur Installer les dépendances dans les options en haut à gauche.
