### ISSUE TITLE
Le fichier python "launcher" ne s'ouvre pas

### ISSUE THREAD

**Issue by XoriFox** [JacqueSatan/Discord-bot#6]
Tout est dans le titre. Voici ce que sa m'affiche : un message avec ecris dessus "L'application n'a pas reussi à démarrer correctement (0*c000007b). Cliquez sur OK pour fermer l'application." le titre du msg est "pythonw.exe - erreur d'application"

cordialement

**Comment by JacqueSatan** [comment]
D'après moi, il y a deux solutions. 

# 1er Cas  : Tu n'as pas la bonne version de python

- L'application ne fonctionne pas sous python 2, et je ne suis pas certain de la compatibilité avec les versions précédentes à python 3.6. Il faut donc désinstaller la version que tu as et repasser sur une plus récente.

# 2eme Cas : Il manque une dépendance
- Tu n'as peut-être pas installé l'addition tKinter lors de l'installation. Il suffirait alors de relancer le setup de python, de cliquer sur "Modify" et de tout cocher.

Si cela ne marche pas, donne-moi plus d'informations, comme une capture d'écran ou encore mieux, une vidéo. Donne-moi aussi la version de python que tu as si possible.

Merci d'avance, Jacques
