### ISSUE TITLE
Problème dépendances & Token "Invalide"

### ISSUE THREAD

**Issue by Kezua** [JacqueSatan/Discord-bot#7]
Bonjour quand je rentre le token de mon BOT et que je clique sur rechercher les erreurs ça me dis que le token et invalide alors que je l'ai bien copié de mon bot donc je vois pas pourquoi il est invalide et que les dépendances ne sont pas installés, alors que pourtant j'ai discord sur windows, nodeJS, python 3.7 du coup je comprend pas

**Comment by Savonnette3239** [comment]
Salut ouvre l'appli et va dans options et tu clique sur installer les dépendances

**Comment by Savonnette3239** [comment]
Sinon utilise cette version https://github.com/JacqueSatan/Discord-bot/tree/v1.4.2
