### ISSUE TITLE
Problème | Bug

### ISSUE THREAD

**Issue by AzizPilote** [JacqueSatan/Discord-bot#8]
Bonjour, svp Aidez moi ! Quand je veux connecter mon BOT sur mon serveur, les serveurs ne veulent pas s'afficher.  HELP ME ! Please aidez-moi ... Voici mon discord au cas ou : ▂▃▅▆Ħǻ¢ќǿǘ$©®▆▅▃▂#9620

**Comment by JacqueSatan** [comment]
Bonjour, merci de préciser l'erreur ; soit tu vis dans un autre monde, soit tu t'es trompé d'application, mais connecter son bot sur un serveur ne veut rien dire, et ce qui suit non plus.
