### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by JockeRider199** [JacqueSatan/Discord-bot#9]
C'est écrit que le version d'essai est finie :( 
je pensais c'étais à vie ...

**Comment by JacqueSatan** [comment]
C'est à vie, mais merci de ne pas polluer les issues avec ce type de messages.

**Comment by JockeRider199** [comment]
Pourriez -vous me déban de discord jsp pq vous pensez que je suis une
taupe…Mais une taupe n'utlise pas votre logiciel … Juste car j'ai été sur
le serveur anti raid pour leur bot...

Merci

**Comment by JacqueSatan** [comment]
C'est bon
